name: Release

env:
  PROXYGEN_CLIENT_ID: ${{ secrets.PROXYGEN_CLIENT_ID }}
  PROXYGEN_CLIENT_SECRET: ${{ secrets.PROXYGEN_CLIENT_SECRET }}

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install deps
        run: |
          sudo apt install gnome-keyring

      - name: install poetry
        run: pip install --upgrade pip && pip install poetry

      - name: set poetry credentials
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: build
        run: poetry build

      - name: publish
        run: |
          sed -i "s/PROXYGEN_CLIENT_ID = \"\"/PROXYGEN_CLIENT_ID = \"$PROXYGEN_CLIENT_ID\"/" proxygen_cli/lib/constants.py
          sed -i "s/PROXYGEN_CLIENT_SECRET = \"\"/PROXYGEN_CLIENT_SECRET = \"$PROXYGEN_CLIENT_SECRET\"/" proxygen_cli/lib/constants.py
          poetry publish
