name:  ci-checks

on:
  pull_request:
    branches:
      - "*"
jobs:
  build:
    name: ci-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install poetry
        if: always()
        run: pip install --upgrade pip && pip install poetry

      - name: Install dependencies
        if: always()
        run: python -m poetry install

      - name: Pytest
        if: always()
        run: make pytest-ci
